# permissions for end users to edit infobloxippools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infobloxippool-editor-role
rules:
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - infobloxippools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - infobloxippools/status
  verbs:
  - get
